/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package com.qianyan.search.express.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.qianyan.search.express.web.form.PatentclassForm;

/**
 * MyEclipse Struts Creation date: 05-13-2008 XDoclet definition:
 * 
 * @struts.action path="/patentclass" name="patentclassForm" input="/patentclass.jsp" scope="request" validate="true"
 */
public class PatentclassAction extends Action {
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request, HttpServletResponse response) {
        PatentclassForm patentclassForm = (PatentclassForm) form;// TODO Auto-generated method stub
        return null;
    }
}