/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package biz.qianyan.search.express.web.form;

import java.net.URLEncoder;
import java.util.Calendar;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.util.LabelValueBean;

/**
 * MyEclipse Struts Creation date: 04-23-2008 XDoclet definition:
 * 
 * @struts.form name="patentForm"
 */
public class PatentForm extends ActionForm {
    /*
     * Generated fields
     */
    private Vector<LabelValueBean> provinceselect;

    private String                 province;

    /** q property */
    private String                 q;

    /** p property */
    private Integer                p;
    /** class */
    private int                    c;
    private String                 sc;
    /** encoded query */
    private String                 eq;
    /** sort flag */
    private int                    s = 1;
    /** type */
    private int                    t;

    private int                    r;

    private int                    opend;

    private int                    applyd;

    private Vector<LabelValueBean> openselect;
    private Vector<LabelValueBean> applyselect;

    /*
     * Generated Methods
     */

    /**
     * Method validate
     * 
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    public int getOpend() {
        return opend;
    }

    public Vector<LabelValueBean> getOpenselect() {
        return openselect;
    }

    public void setOpenselect(Vector<LabelValueBean> openselect) {
        this.openselect = openselect;
    }

    public Vector<LabelValueBean> getApplyselect() {
        return applyselect;
    }

    public void setApplyselect(Vector<LabelValueBean> applyselect) {
        this.applyselect = applyselect;
    }

    public void setOpend(int opend) {
        this.opend = opend;
    }

    public int getApplyd() {
        return applyd;
    }

    public void setApplyd(int applyd) {
        this.applyd = applyd;
    }

    public Vector<LabelValueBean> getProvinceselect() {
        return provinceselect;
    }

    public void setProvinceselect(Vector<LabelValueBean> provinceselect) {
        this.provinceselect = provinceselect;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * Method reset
     * 
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        setT(1);
        setP(1);
        setC(0);
        setR(0);
        openselect = new Vector<LabelValueBean>();
        applyselect = new Vector<LabelValueBean>();
        openselect.add(new LabelValueBean("所有公开年份", "-1"));
        applyselect.add(new LabelValueBean("所有申请年份", "-1"));
        Calendar cal = Calendar.getInstance();
        int curyear = cal.get(Calendar.YEAR);
        for (int i = curyear; i > 1984; i--) {
            openselect.add(new LabelValueBean(i + "年", i + ""));
            applyselect.add(new LabelValueBean(i + "年", i + ""));
        }
    }

    public int getR() {
        return r;
    }

    public void setR(int r) {
        this.r = r;
    }

    /**
     * Returns the q.
     * 
     * @return String
     */
    public String getQ() {
        return q;
    }

    /**
     * Set the q.
     * 
     * @param q
     *            The q to set
     */
    public void setQ(String q) {
        this.q = q;
        try {
            this.eq = URLEncoder.encode(q, "GBK");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Returns the p.
     * 
     * @return Integer
     */
    public Integer getP() {
        return p;
    }

    /**
     * Set the p.
     * 
     * @param p
     *            The p to set
     */
    public void setP(Integer p) {
        this.p = p;
    }

    public int getC() {
        return c;
    }

    public void setC(int c) {
        this.c = c;
        setSc(c);
    }

    public String getEq() {
        return eq;
    }

    public int getS() {
        return s;
    }

    public void setS(int s) {
        this.s = s;
    }

    public int getT() {
        return t;
    }

    public void setT(int t) {
        this.t = t;
    }

    public String getSc() {
        return sc;
    }

    private void setSc(int t) {
        switch (t) {
            case 0:
                sc = "所有专利";
                break;
            case 1:
                sc = "发明专利";
                break;
            case 2:
                sc = "实用新型专利";
                break;
            case 3:
                sc = "外观专利";
                break;
            case 8:
                sc = "国外发明专利";
                break;
            default:
                sc = "所有专利";
                break;

        }
    }

}